### ISSUE TITLE
Terceira Avaliação por Pares

### ISSUE THREAD

**Issue by mileneserrano** [UnBArqDsw2020-2/2020.2_G1_CabeleleiraLeila#101]
Olá Pessoal!

O Grupo 01 irá avaliar o Grupo 03 nessa terceira avaliação por pares.
Os templates, em doc ou pdf, e demais informações para essa avaliação constam disponíveis no Moodle.
Basta entrar no Tópico 2 DSW(Padrões de Projeto) da trilha do Moodle, e procurar por "Terceira Avaliação por Pares".

Atenciosamente.

**Comment by ErickGiffoni** [comment]
ok

**Comment by brunaalmeidasantos** [comment]
Terceira avaliação por pares concluída no dia 12/04/2021, por meio de reunião com todos os integrantes do grupo.
