### ISSUE TITLE
Introdução

### ISSUE THREAD

**Issue by RafaellaJunqueira** [UnBArqDsw2020-2/2020.2_G1_CabeleleiraLeila#104]
### Descrição:
A introdução do documento é composta por vários tópicos. A cada sprint os itens devem ser marcados como feitos.

### Tarefas:
- [x] Propósito (purpose) Sprint 7 #88
- [x] Escopo (scope) Sprint 7 #88
- [x] Definições (Definitions, Acronyms, and Abbreviations)
- [x] Referências (References)
- [x] Visão geral (Overview)

**Comment by ErickGiffoni** [comment]
Começando 👍🏻

**Comment by ErickGiffoni** [comment]
1.1 Propósito feito 👍🏻

**Comment by ErickGiffoni** [comment]
1.2 Escopo iniciado 👍🏻
