### ISSUE TITLE
Visão de Implementação

### ISSUE THREAD

**Issue by brunaalmeidasantos** [UnBArqDsw2020-2/2020.2_G1_CabeleleiraLeila#113]
### Descrição:
Criar o documento relacionado à Visão de Implementação para o documento de arquitetura.

### Tarefas:

- [x]  Fazer introdução
- [x] Falar sobre o front-end
- [x] Falar sobre o back-end

**Comment by ErickGiffoni** [comment]
tópico 8.2 escrito 👍🏻
