### ISSUE TITLE
Backlog do produto - Níveis de abstração

### ISSUE THREAD

**Issue by RafaellaJunqueira** [UnBArqDsw2020-2/2020.2_G1_CabeleleiraLeila#12]
### Descrição:
Modelar cada nível de abstração exigido, um em cada documento.

### Critérios de aceitação:
- Mínimo 3 níveis de rastreabilidade;
- Deve conter histórico de versão.

### Tarefas:
- [x] Criar um documento para Features
- [x] Criar um documento para Story
- [x] Cirar um documento para Task
- [x] Critério de aceitação (se der tempo)

**Comment by ErickGiffoni** [comment]
Backlog ok 👍🏻
