### ISSUE TITLE
Backlog do produto - Priorização

### ISSUE THREAD

**Issue by RafaellaJunqueira** [UnBArqDsw2020-2/2020.2_G1_CabeleleiraLeila#17]
### Descrição:
O backlog do produto deve conter todos os requisitos levantados e suas 

### Critérios de aceitação
- Deve haver rastreabilidade em cada requisito
- Deve conter histórico de versão
- Deve conter referências

### Tarefas:
- [x] Agrupar todos os requisitos elicitados (separado em funcionais e não funcionais)
- [x] Priorizar os requisitos usando MoSCoW
- [x] Pra cada requisito, colocar o link de rastreabilidade pro artefato de onde ele foi levantado
- [ ] Priorizar os requisitos usando First Thing First (caso dê tempo)

**Comment by ErickGiffoni** [comment]
O backlog foi feito 👍🏻
