### ISSUE TITLE
Gravar vídeo - Design Sprint

### ISSUE THREAD

**Issue by RafaellaJunqueira** [UnBArqDsw2020-2/2020.2_G1_CabeleleiraLeila#20]
### Descrição:
Vídeo explicando passo a passo a Design Sprint realizada, com: (i) rastro claro aos membros participantes; (ii) justificativas & senso crítico sobre o trabalho realizado; (iii) breve apresentação dos artefatos elaborados, e (iv) comentários gerais sobre iniciativas extras. Tempo do vídeo: +/- 15min. 
Recomendação: Apresentar diretamente via Wiki ou GitPages do Projeto.

### Tarefas
- [x] Combinar dia e horário para a gravação
- [x] Colocar o vídeo na wiki

OBS.: Essa entrega é composta por 2 partes: Módulo Projeto Não Orientado a Abordagens Específicas e Módulo Processos/Metodologias/Abordagens. O vídeo dessa issue (Design Sprint) se refere ao primeiro módulo.

**Comment by ErickGiffoni** [comment]
Gravação feita 👍🏻
