### ISSUE TITLE
Gravar vídeo - Metodologias

### ISSUE THREAD

**Issue by RafaellaJunqueira** [UnBArqDsw2020-2/2020.2_G1_CabeleleiraLeila#21]
### Descrição:
Vídeo explicando o detalhamento metodológico desenhado, com: (i) rastro claro aos membros participantes; (ii) justificativas & senso crítico sobre as escolhas metodológicas adotadas para o projeto; (iii) breve apresentação do(s) artefato(s) de modelagem em BPMN, e (iv) comentários gerais sobre iniciativas extras. Tempo do vídeo: +/- 15min. 

Recomendação: Apresentar diretamente via Wiki ou GitPages do Projeto.

### Tarefas:
- [x] Combinar dia e horário para gravar vídeo
- [x] Colocar o vídeo na wiki

### Finalizar documento da entrega !!!
A entrega deverá ser em arquivo único (ZIP) com, no mínimo:
- [x] Documento em pdf com a identificação do grupo, nome do projeto e detalhamento dos membros da equipe do projeto
- [x] Link para o repositório do projeto, com pleno acesso sobre os conteúdos, wiki, código e participação dos membros,
- [x] link(s) para o(s) VÍDEO(S), conforme as Diretrizes indicam. Adicionalmente, mantenham o(s) vídeo(s) no repositório principal do grupo, na Organização da Disciplina no GitHub

**Comment by ErickGiffoni** [comment]
Gravação feita 👍🏻
