### ISSUE TITLE
Reunião 2 [12 de fevereiro ]

### ISSUE THREAD

**Issue by RafaellaJunqueira** [UnBArqDsw2020-2/2020.2_G1_CabeleleiraLeila#22]
<table>
  <tr>
    <td colspan='9'><center><b>Reunião 2</b></td>
  </tr>
  <tr>
    <td colspan='2'><b>Data: </b></td>
    <td colspan='7'>12 de fevereiro de 2021</td>
  </tr>

  <tr>
    <td colspan='2'><b>Discussão:</b></td>
    <td colspan='7'> - Sprint Planning + Daily<br> - Vamos realmente fazer aqueles 3 níveis de granularidade definidos antes pro backlog?<br>- O BPMN é pra essa entrega?<br>- Temos que fazer o teste com o protótipo<br>- Gravar os vídeos</td>
  </tr>
  <tr>
    <td colspan='2'><b>Conclusão:</b></td>
    <td colspan='7'>- Manter os 3 níveis de granularidade definidos antes<br>- BPMN é para ser feito agora<br>- Ver com a Isa se o protótipo ta pronto pra ser testado</td>
  </tr>

  <tr>
    <td colspan='2'><b>Início:</b></td>
    <td colspan='7'>18h05</td>
  </tr>
  <tr>
    <td colspan='2'><b>Término:</b></td>
    <td colspan='7'>19h</td>
  </tr>

   <tr>
    <td colspan='9'><center><b>Integrantes</b></td>
  </tr>
  <tr>
    <td colspan='2'><b><center>Nome</b></td>
    <td colspan='1'><b><center>Presença</b></td>
    <td colspan='5'><b><center>Justificativa</b></td>
  </tr>
   <tr>
    <td colspan='2'>Bruna Almeida</td>
    <td colspan='1'><center><b>✔️</b></td>
    <td colspan='5'></td>
  </tr>
  <tr>
    <td colspan='2'>Damarcones Porto</td>
    <td colspan='1'><center><b>✔️</b></td>
    <td colspan='5'></td>
  </tr>
  <tr>
    <td colspan='2'>Erick Giffoni</td>
    <td colspan='1'><center><b>✔️</b></td>
    <td colspan='5'></td>
  </tr>
  <tr>
    <td colspan='2'>Geraldo Victor</td>
    <td colspan='1'><center><b>✔️</b></td>
    <td colspan='5'></td>
  </tr>
  <tr>
    <td colspan='2'>Isabella Carneiro</td>
    <td colspan='1'><center><b>✖️</b></td>
    <td colspan='5'>Caiu a conexão</td>
  </tr>
 <tr>
    <td colspan='2'>Kalebe Lopes</td>
    <td colspan='1'><center><b>✔️</b></td>
    <td colspan='5'></td>
  </tr>
 <tr>
    <td colspan='2'>Lucas Lopes</td>
    <td colspan='1'><center><b>✔️</b></td>
    <td colspan='5'></td>
  </tr>
 <tr>
    <td colspan='2'>Rafaella Junqueira</td>
    <td colspan='1'><center><b>✔️</b></td>
    <td colspan='5'></td>
  </tr>
</table>

**Comment by ErickGiffoni** [comment]
Bora, hoje 18h, certo ?
