### ISSUE TITLE
Diagrama de Agregação e Composição

### ISSUE THREAD

**Issue by RafaellaJunqueira** [UnBArqDsw2020-2/2020.2_G1_CabeleleiraLeila#52]
## Criação do Diagrama de Agregação e Composição

- [x] Fazer o diagrama de acordo com as classes previamente projetadas no Diagrama de Classes #46 
- [x] Documentar o que foi feito no gh-pages

**Comment by ErickGiffoni** [comment]
Eu e @LucasPLopes acabamos de fazer a modelagem usando o diagrams.net
Falta escrevermos no pages 👍🏻

**Comment by ErickGiffoni** [comment]
Começando a documentação no gh-pages 🚀

**Comment by ErickGiffoni** [comment]
Finalizada a documentação!

**Comment by ErickGiffoni** [comment]
Pull request aprovado e deploy feito 👍🏻
