### ISSUE TITLE
Diagrama relacional

### ISSUE THREAD

**Issue by RafaellaJunqueira** [UnBArqDsw2020-2/2020.2_G1_CabeleleiraLeila#55]
## Criação do Diagrama relacional (banco de dados)

**Comment by ErickGiffoni** [comment]
Terça-feira eu e @KalebeLopes  nos reunimos e discutimos sobre o ME-R, DE-R, DE, DLD.
Adiantamos o ME-R

**Comment by ErickGiffoni** [comment]
Hoje estou desenhando o DE-R. Kalebe deve se juntar comigo mais tarde

**Comment by ErickGiffoni** [comment]
Ontem o Kalebe consegui finalizar o DE-R. Ainda falta gerarmos o DLD. A ferramenta CASE utilizada passou a ser o brModelo

**Comment by LucasPLopes** [comment]
Atualização repassada para main, issue concluida.
