### ISSUE TITLE
Backlog do Produto (Continuação)

### ISSUE THREAD

**Issue by RafaellaJunqueira** [UnBArqDsw2020-2/2020.2_G1_CabeleleiraLeila#58]
## Completar Backlog do Produto

**Comment by ErickGiffoni** [comment]
Ontem trabalhei com ajustes ao backlog. Além disso uma nova coluna foi adicionada, referente aos épicos

**Comment by ErickGiffoni** [comment]
Hoje estou realizando mais ajustes finos e adicionando os rastros dos requisitos

**Comment by ErickGiffoni** [comment]
Backlog finalizado. Falta atualizar o documento no gh-pages 👍🏻

**Comment by ErickGiffoni** [comment]
Documento do Backlog finalizado 👍🏻 . Aguardo revisão dos colegas.

**Comment by ErickGiffoni** [comment]
Fechando agora 👍🏻
