### ISSUE TITLE
Feedback Entrega 1 - Micaella

### ISSUE THREAD

**Issue by micaellagouveia** [UnBArqDsw2020-2/2020.2_G1_CabeleleiraLeila#61]
Feedback G1 - Micaella

* Design Sprint
	* Boa documentação
	* Bons rastros de documentos
	* participação de apenas 2 integrantes

* Protótipo de Baixa fidelidade
	* quem fez o protótipo?, como foi esse processo? de onde vcs tiraram os requisitos para montar o protótipo?
	* Quem testou seu protótipo? quais foram as conclusões tiradas?
	* Só um participante :(

* Protótipo de alta fidelidade
	* O protótipo de alta fidelidade deve ser uma evolução do de baixa, com as melhorias que foram propostas, quais foram as melhorias? quem testou o de baixa pra se ter o de alta? 
	* Mais pessoas participaram :)

* Metodologia
	* boa documentação, muitos participam

* BPMN
	* só uma pessoa participa em uma entrega de mtttt peso na 1a entrega, prof pode descontar pontos aqui :(
	* Dica: colocar um acesso ao pdf dos arquivos, pois fica difícil a leitura
	* faltou os áudios explicando cada diagrama
	* não há quem fez cada diagrama

* Identidade visual
	* extra mt bem feito, padrão mt parecido com o do G12 do semestre passado, se for usado como base, tem que ter referência. Se atentem a essa referência, grupos semestre passados perderam nota de estética por copiarem outros e não referenciarem!!!

* Requisitos
	* Rich picture -> legal a doc, mas 2 alunos participam :(, por ser um dos 1os artefatos q se faz, aquele q vai ter a visao geral de todo o projeto, é ESSENCIAL que todos os membros participem, tanto para rich picture, mapa mental, etc.
	* 5W2H -> ficou mt bom, bem clean, mas faltou participantes
	* Mapa mental -> só um mapa mental, sem autor, esse é o documento q tem q ter de todos, e um geral
	* Causa-efeito -> só um diagrama, artefato q deve ser usado para varios aspectos do projeto, mas ficou bem feito
	* Plano de riscos -> ficou mt legal, bem organizado

* Elicitação
	* brainstorming -> mt bom
	* questionario -> quais os requisitos levantados?
	* entrevista -> mt bom, rastro legal, tem q ter o padrão de rastros para os outros documentos
	* MOSCOW -> não é elicitação e sim priorização. Só tem os requisitos do brainstorming? onde posso ver todos os requisitos de tudo?
	* Backlog -> quais são as features? e os épicos?

** Obs Importantes
* Padrão na documentação - alguns tem rastro nos nomes, participantes, e outros docs não.
* Participação significativa nos artefatos - não é legal ter só 1 membro fazendo um artefato.
* Rastros - manter um padrão de rastros
* Metodologias sempre bem definidas: como foi feito, pq foi feito assim, quem participou...
* Nome de autores dos diagramas, imagens, etc.
* Organização das Sprints - não tem :(
* Referencias para repos - referenciar repos antigos que são usados como base
* pdf para imagens - melhor visualização
* discrepância na contribuição -> isso é mt problemático

**Comment by ErickGiffoni** [comment]
Obrigado pelo feedback !
