### ISSUE TITLE
Reunião 3 [ 26 de fevereiro ] - Dicas Micaella

### ISSUE THREAD

**Issue by RafaellaJunqueira** [UnBArqDsw2020-2/2020.2_G1_CabeleleiraLeila#63]
<table>
  <tr>
    <td colspan='9'><center><b>Reunião 3</b></td>
  </tr>
  <tr>
    <td colspan='2'><b>Data: </b></td>
    <td colspan='7'>26/02</td>
  </tr>

  <tr>
    <td colspan='2'><b>Discussão:</b></td>
    <td colspan='7'>Alinhamento do projeto</td>
  </tr>
  <tr>
    <td colspan='2'><b>Conclusão:</b></td>
    <td colspan='7'>FEEDBACK & DICAS:<br>✏️ Colocar no PDF da entrega o que foi feito e o que é extra;<br>✏️ Fazer uma reunião com todos os participantes durante a criação de um documento, mas pode responsabilizar uma só pessoa pela documentação dele;<br>✏️ Rotatividade de quem criou o documento pela primeira e quem vai fazer a melhoria futura;<br>✏️ Referenciar caso sejam usados repositórios de outros grupos;<br>✏️ Refatorar documentos de requisitos (mesmo que se repitam, colocar lá pra entrar na rastreabilidade do backlog);<br><br>PADRONIZAÇÃO DOS DOCUMENTOS:<br>✏️ Incluir item de participantes em todos os documentos<br>✏️ Todo documento deve ter: <br>-  introdução (o que é aquele artefato)<br>- metodologia (como foi feito, o processo no projeto)<br>- resultados (o que foi feito mesmo)<br>- Referências <br>✏️ Revisou o documento? insira seu nome na tabela de versionamento</td>
  </tr>

  <tr>
    <td colspan='2'><b>Início:</b></td>
    <td colspan='7'>18h</td>
  </tr>
  <tr>
    <td colspan='2'><b>Término:</b></td>
    <td colspan='7'>19h30</td>
  </tr>

   <tr>
    <td colspan='9'><center><b>Integrantes</b></td>
  </tr>
  <tr>
    <td colspan='2'><b><center>Nome</b></td>
    <td colspan='1'><b><center>Presença</b></td>
    <td colspan='5'><b><center>Justificativa</b></td>
  </tr>
   <tr>
    <td colspan='2'>Bruna Almeida</td>
    <td colspan='1'><center><b></b>✔️</td>
    <td colspan='5'></td>
  </tr>
  <tr>
    <td colspan='2'>Damarcones Porto</td>
    <td colspan='1'><center><b></b>✔️</td>
    <td colspan='5'></td>
  </tr>
  <tr>
    <td colspan='2'>Erick Giffoni</td>
    <td colspan='1'><center><b></b>✔️</td>
    <td colspan='5'></td>
  </tr>
  <tr>
    <td colspan='2'>Geraldo Victor</td>
    <td colspan='1'><center><b></b>✔️</td>
    <td colspan='5'></td>
  </tr>
  <tr>
    <td colspan='2'>Isabella Carneiro</td>
    <td colspan='1'><center><b></b>✔️</td>
    <td colspan='5'></td>
  </tr>
 <tr>
    <td colspan='2'>Kalebe Lopes</td>
    <td colspan='1'><center><b></b>✔️</td>
    <td colspan='5'></td>
  </tr>
 <tr>
    <td colspan='2'>Lucas Lopes</td>
    <td colspan='1'><center><b></b>✔️</td>
    <td colspan='5'></td>
  </tr>
 <tr>
    <td colspan='2'>Rafaella Junqueira</td>
    <td colspan='1'><center><b></b>✔️</td>
    <td colspan='5'></td>
  </tr>
 <tr>
    <td colspan='2'>Micaella Gouveia (Monitora)</td>
    <td colspan='1'><center><b></b>✔️</td>
    <td colspan='5'></td>
  </tr>
</table>

**Comment by ErickGiffoni** [comment]
Reunião muito boa, e com o feedback da @micaellagouveia foi melhor ainda
