### ISSUE TITLE
Rich Pictures

### ISSUE THREAD

**Issue by RafaellaJunqueira** [UnBArqDsw2020-2/2020.2_G1_CabeleleiraLeila#8]
### Descrição:
As Rich Pictures servem para ilustrar e trazer uma melhor compreensão do problema a ser resolvido pela equipe de desenvolvimento.

**Comment by ErickGiffoni** [comment]
Os rich pictures estão feitos

**Comment by ErickGiffoni** [comment]
Falta ainda: Rich Picture versão 3 - usando alguma ferramenta de desenho e relacionando com o mapa mental

**Comment by ErickGiffoni** [comment]
Hoje eu e o @damarcones nos reunimos e finalizamos o Rich Picture versão 3 usando a ferramenta Canva !
