### ISSUE TITLE
Cadastrar serviços

### ISSUE THREAD

**Issue by RafaellaJunqueira** [UnBArqDsw2020-2/2020.2_G1_CabeleleiraLeila#90]
### Descrição:
Criar um crud para cadastro de serviços do salão.

### Critérios de aceitação:
- Este documento deve conter tabela de versão
- Este documento deve conter referências bibliográficas
- Criar a modelagem UML do padrão utilizado

### Tarefas
- [x] Criar serviço
- [x] Visualizar serviço
- [x] Atualizar serviço

Dívidas técnicas dessa issue:
- [x] Deletar serviço
- [x] CORS do update

**Comment by ErickGiffoni** [comment]
Estamos em progresso 👍🏻 eu e Kalebe

**Comment by KalebeLopes** [comment]
Rotas get e post criadas!

**Comment by ErickGiffoni** [comment]
Nos reunimos ontem e discutimos padrões de projeto e de arquitetura que estão sendo utilizados 👍🏻 
`participantes = [ Erick, @RafaellaJunqueira, @KalebeLopes ]`

**Comment by ErickGiffoni** [comment]
Bom dia, acabei de finalizar a edição e revisão final da primeira versão do documento Grasp Controller

**Comment by ErickGiffoni** [comment]
Editei e revisei o documento Grasp Baixo Acoplamento 👍🏻
