### ISSUE TITLE
Visualizar serviços

### ISSUE THREAD

**Issue by RafaellaJunqueira** [UnBArqDsw2020-2/2020.2_G1_CabeleleiraLeila#96]
### Descrição:
Essa issue foi modificada pois está dentro da issue 90.

**Comment by KalebeLopes** [comment]
isso está sendo feito na issue #90, o código está na branch cadastrar-servicos

**Comment by ErickGiffoni** [comment]
Bom dia, acabei de finalizar a edição e revisão final da primeira versão do documento Grasp Controller

**Comment by ErickGiffoni** [comment]
Editei e revisei o documento Grasp Baixo Acoplamento 👍🏻
